### ISSUE TITLE
Example of TSV SNP data (.txt) for input variant call snp data

### ISSUE THREAD

**Issue by danielleingle** [phac-nml/cladeomatic#6]
Hello. Do you have an example of the file format for SNP data in txt format? Instructions say input can be either vcf or tabular format. We would prefer to use tabular - what does this need to look like? Thanks

**Comment by jrober84** [comment]
Hello,

Cladeomatic can use the output from SNVPhyl (Tab) https://snvphyl.readthedocs.io/en/latest/user/output/ directly and vcf produced  by tools like Snippy https://github.com/tseemann/snippy.  Hope that helps
